{"issue":{"id":7166,"project":{"id":1,"name":"Ceph"},"tracker":{"id":1,"name":"Bug"},"status":{"id":3,"name":"Resolved"},"priority":{"id":6,"name":"Urgent"},"author":{"id":789,"name":"Loic Dachary"},"assigned_to":{"id":461,"name":"Joao Luis"},"category":{"id":3,"name":"Monitor"},"subject":"mon: Error ENOENT: unrecognized pool 'data' on a new cluster","description":"After compiling todays \"master from sources\":https://github.com/ceph/ceph/commit/3b696f28d6cee1fd3a2b78911cc8377445158ba1\r\n<pre>\r\nloic@fold:~/software/ceph/ceph/src$ rm -fr dev out ;  mkdir -p dev ; LC_ALL=C MON=1 OSD=3 bash -x ./vstart.sh -d -n -X -l mon osd\r\nloic@fold:~/software/ceph/ceph/src$ ./ceph -s\r\n*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***\r\n    cluster 148b1b70-d0d5-484a-bca9-bb1a03dea423\r\n     health HEALTH_WARN 7 pgs peering; 6 pgs stuck inactive; 13 pgs stuck unclean; too few pgs per osd (8 < min 10)\r\n     monmap e1: 1 mons at {a=127.0.0.1:6789/0}, election epoch 2, quorum 0 a\r\n     osdmap e9: 3 osds: 3 up, 3 in\r\n      pgmap v11: 24 pgs, 3 pools, 0 bytes data, 0 objects\r\n            294 GB used, 71863 MB / 364 GB avail\r\n                   6 creating\r\n                  11 active+clean\r\n                   7 peering\r\nloic@fold:~/software/ceph/ceph/src$ ./ceph -s\r\n*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***\r\n    cluster 148b1b70-d0d5-484a-bca9-bb1a03dea423\r\n     health HEALTH_WARN too few pgs per osd (8 < min 10)\r\n     monmap e1: 1 mons at {a=127.0.0.1:6789/0}, election epoch 2, quorum 0 a\r\n     osdmap e9: 3 osds: 3 up, 3 in\r\n      pgmap v15: 24 pgs, 3 pools, 0 bytes data, 0 objects\r\n            441 GB used, 105 GB / 547 GB avail\r\n                  24 active+clean\r\nloic@fold:~/software/ceph/ceph/src$ ./rados lspools\r\ndata\r\nmetadata\r\nrbd\r\nloic@fold:~/software/ceph/ceph/src$ ./ceph osd pool set data size 1\r\n*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***\r\nError ENOENT: unrecognized pool 'data'\r\nloic@fold:~/software/ceph/ceph/src$ \r\n</pre>\r\nThe same failure can be seen when \"gitbuilder runs make check\":http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-tarball-precise-amd64-basic/log.cgi?log=3b696f28d6cee1fd3a2b78911cc8377445158ba1","start_date":"2014-01-16","done_ratio":100,"spent_hours":0.0,"custom_fields":[{"id":1,"name":"Source","value":"Community (dev)"},{"id":2,"name":"Backport","value":""},{"id":3,"name":"Tags","value":""},{"id":4,"name":"Severity","value":"3 - minor"},{"id":5,"name":"Reviewed","value":""}],"created_on":"2014-01-16T10:02:33Z","updated_on":"2014-01-16T13:23:19Z",
"journals":[{"id":31009,"user":{"id":461,"name":"Joao Luis"},"notes":"This breaks current master (3b696f28d6cee1fd3a2b78911cc8377445158ba1). Might have something to do with the changes introduced by wip-temp-primary.","created_on":"2014-01-16T10:16:15Z","details":[]},{"id":31011,"user":{"id":461,"name":"Joao Luis"},"notes":"wip-7166, pr https://github.com/ceph/ceph/pull/1095\r\n\r\nWaiting for the gitbuilders to pass the make checks.","created_on":"2014-01-16T12:53:46Z","details":[]},{"id":31013,"user":{"id":789,"name":"Loic Dachary"},"notes":"","created_on":"2014-01-16T13:23:19Z","details":[]}],
"attachments":[],"relations":[]}}
